defaults:
  elective: true
  adult: true
  allergy: false
  outpatient: false

maßnahmen:
  allgemeine_risiken:
    respiratorisch:
      - id: aspiration
        de: "Aspiration"
        en: "Aspiration"
        fr: "Aspiration"
      - id: bronchospasmus
        de: "Broncho-/Laryngospasmus"
        en: "Broncho-/laryngospasm"
        fr: "Broncho-/laryngospasme"
      - id: schwieriger_atemweg
        de: "Schwieriger Atemweg"
        en: "Difficult airway"
        fr: "Voies respiratoires difficiles"
      - id: hypoxie
        de: "Hypoxie"
        en: "Hypoxia"
        fr: "Hypoxie"
      - id: pneumonie
        de: "Aspirationspneumonie"
        en: "Aspiration pneumonia"
        fr: "Pneumonie d’aspiration"

    kardiovaskulär:
      - id: hypotension
        de: "Hypotonie"
        en: "Hypotension"
        fr: "Hypotension"
      - id: hypertension
        de: "Hypertensive Krise"
        en: "Hypertensive crisis"
        fr: "Crise hypertensive"
      - id: tachykardie
        de: "Tachykardie"
        en: "Tachycardia"
        fr: "Tachycardie"
      - id: herzstillstand
        de: "Herzstillstand"
        en: "Cardiac arrest"
        fr: "Arrêt cardiaque"
      - id: infarkt
        de: "Myokardinfarkt / Schlaganfall"
        en: "Myocardial infarction / stroke"
        fr: "Infarctus / AVC"

    allgemein_medikamentös:
      - id: überempfindlichkeit
        de: "Allergische Reaktion bis anaphylaktischer Schock"
        en: "Allergic reaction up to anaphylactic shock"
        fr: "Réaction allergique jusqu’au choc anaphylactique"
      - id: maligne_hyperthermie
        de: "Maligne Hyperthermie"
        en: "Malignant hyperthermia"
        fr: "Hyperthermie maligne"
      - id: awareness
        de: "Wachheit unter Narkose (Awareness)"
        en: "Intra-operative awareness"
        fr: "Conscience per-opératoire"
      - id: übelkeit_ponv
        de: "Übelkeit / Erbrechen (PONV)"
        en: "Nausea / vomiting"
        fr: "Naussées / vomissements"

  airway_management:
    masken_tubus:
      - id: zahnverletzung
        de: "Zahn-, Prothesen-, Implantatschäden"
        en: "Dental / prosthetic injury"
        fr: "Lésion dentaire / prothétique"
      - id: halsschmerzen_heiserkeit
        de: "Halsschmerzen / Heiserkeit"
        en: "Sore throat / hoarseness"
        fr: "Maux de gorge / enrouement"
      - id: trachealverletzung
        de: "Rachen-/Larynx-/Trachealverletzung"
        en: "Pharyngeal / laryngeal / tracheal injury"
        fr: "Lésion pharyngo-laryngée / trachéale"
      - id: corneaschaden
        de: "Hornhautschaden"
        en: "Corneal injury"
        fr: "Lésion cornéenne"

  lines_catheters:
    zvk:
      - id: pneumothorax
        de: "Pneumothorax / Hämo- bzw. Chylothorax"
        en: "Pneumo-/hemo-/chylothorax"
        fr: "Pneumo-/hémothorax / chylothorax"
      - id: luftembolie
        de: "Luftembolie"
        en: "Air embolism"
        fr: "Embolie gazeuse"
      - id: hämatom_blutung
        de: "Blutung / Hämatom"
        en: "Bleeding / hematoma"
        fr: "Hémorragie / hématome"
      - id: infektion_sepsis
        de: "Katheterinfektion / Sepsis / Endokarditis"
        en: "Catheter infection / sepsis / endocarditis"
        fr: "Infection du cathéter / septicémie / endocardite"
      - id: thrombose_embolie
        de: "Thrombose / Katheterembolie"
        en: "Thrombosis / catheter embolism"
        fr: "Thrombose / embolie de cathéter"
      - id: arrhythmie
        de: "Herzrhythmusstörungen"
        en: "Cardiac arrhythmia"
        fr: "Trouble du rythme cardiaque"
      - id: herzbeuteltamponade
        de: "Herzbeuteltamponade"
        en: "Cardiac tamponade"
        fr: "Tamponnade cardiaque"
      - id: pinch_off
        de: "\"Pinch-off\"-Syndrom / Katheterbruch"
        en: "Pinch-off syndrome / catheter fracture"
        fr: "Syndrome de pincement / rupture de cathéter"

    art:
      - id: blutung_art
        de: "Blutung / Pseudoaneurysma / Hämatom"
        en: "Bleeding / pseudo-aneurysm / hematoma"
        fr: "Hémorragie / pseudo-anévrisme / hématome"
      - id: ischämie_okklusion
        de: "Ischämie durch Gefäßverschluss"
        en: "Ischemia due to arterial occlusion"
        fr: "Ischémie par occlusion artérielle"
      - id: infektion_art
        de: "Infektion"
        en: "Infection"
        fr: "Infection"

    pvk:
      - id: phlebitis
        de: "Venenentzündung (Phlebitis) / Infiltrat"
        en: "Phlebitis / infiltration"
        fr: "Phlébite / infiltration"
      - id: extravasation
        de: "Paravasat / Gewebsnekrose"
        en: "Extravasation / tissue necrosis"
        fr: "Extravasation / nécrose tissulaire"
      - id: hämatom_blutung_pvk
        de: "Hämatom / Blutung"
        en: "Hematoma / bleeding"
        fr: "Hématome / hémorragie"
      - id: infektion_pvk
        de: "Lokale Infektion"
        en: "Local infection"
        fr: "Infection locale"
      - id: sepsis_pvk
        de: "Sepsis (katheterassoziiert)"
        en: "Catheter-related sepsis"
        fr: "Septicémie liée au cathéter"
      - id: thrombose_embolie_pvk
        de: "Thrombose / Embolie"
        en: "Thrombosis / embolism"
        fr: "Thrombose / embolie"

    blasenkatheter:
      - id: hwi
        de: "Harnwegsinfekt"
        en: "Urinary tract infection"
        fr: "Infection urinaire"
      - id: urethralverletzung
        de: "Urethralverletzung / Striktur"
        en: "Urethral injury / stricture"
        fr: "Lésion urétrale / sténose"
      - id: blutung_dk
        de: "Blutung"
        en: "Bleeding"
        fr: "Hémorragie"

    magensonde:
      - id: epistaxis
        de: "Schleimhautverletzung / Epistaxis"
        en: "Mucosal injury / epistaxis"
        fr: "Lésion muqueuse / épistaxis"
      - id: ösophagusperforation
        de: "Ösophagus-/Magenperforation"
        en: "Esophageal / gastric perforation"
        fr: "Perforation œsophagienne / gastrique"

    tee:
      - id: tee_verletzung
        de: "Ösophagusverletzung / Mediastinitis"
        en: "Esophageal injury / mediastinitis"
        fr: "Lésion œsophagienne / médiastinite"
      - id: zahnschaden_tee
        de: "Zahnschaden / Rachenblutung"
        en: "Dental injury / pharyngeal bleeding"
        fr: "Lésion dentaire / saignement pharyngé"

  regionalverfahren:
    spa: &spa_risks
      - id: postspinaler_kopfschmerz
        de: "Postspinaler Kopfschmerz"
        en: "Post-spinal headache"
        fr: "Céphalée post-spinale"
      - id: hohe_spinal
        de: "Hohe/total Spinalanästhesie → Atemstillstand"
        en: "High/total spinal → respiratory arrest"
        fr: "Spinale haute/totale → arrêt respiratoire"
      - id: infektion_meningitis
        de: "Meningitis / Epidurale Infektion"
        en: "Meningitis / epidural infection"
        fr: "Méningite / infection épidurale"
      - id: spinalhämatom
        de: "Spinalhämatom"
        en: "Spinal hematoma"
        fr: "Hématome spinal"
      - id: hygrom_subdural
        de: "Subdurales Hygrom"
        en: "Subdural hygroma"
        fr: "Hygroma sous-dural"
      - id: abzess_epidural
        de: "Epiduraler Abszess"
        en: "Epidural abscess"
        fr: "Abcès épidural"
      - id: paraplegie
        de: "Paraplegie / Querschnittslähmung"
        en: "Paraplegia"
        fr: "Paraplégie"
      - id: local_toxicity
        de: "LAST (Krampf / Kardiotoxizität)"
        en: "Local anesthetic systemic toxicity (LAST)"
        fr: "Toxicité systémique des AL"
      - id: verfahrenswechsel
        de: "Wechsel auf Allgemeinanästhesie"
        en: "Conversion to general anaesthesia"
        fr: "Conversion en anesthésie générale"
      - id: rescue_block
        de: "Rescue-Block erforderlich"
        en: "Rescue block required"
        fr: "Bloc de secours nécessaire"

    epidural_pda:
      <<: *spa_risks            # erbt identische Risiken + eigene
      - id: pda_katheter_disloziert
        de: "Katheterdislokation / Knick / Bruch"
        en: "Catheter dislocation / kinking / fracture"
        fr: "Dislocation / coudure / rupture de cathéter"
      - id: pda_blockade_hoch
        de: "Hohe PDA → Hypotonie / Ateminsuffizienz"
        en: "High epidural block → hypotension / respiratory insuff."
        fr: "Bloc péridural haut → hypotension / insuffisance resp."
      - id: pneumo_pda
        de: "Pneumothorax (thorakale PDA)"
        en: "Pneumothorax (thoracic epidural)"
        fr: "Pneumothorax (PDA thoracique)"

    nervenblock:
      - id: nervenschaden
        de: "Nervenschädigung / Neuralgie / Paresen"
        en: "Nerve injury / neuralgia / paresis"
        fr: "Lésion nerveuse / névralgie / parésie"
      - id: diaphragma_lähmung
        de: "Phrenikuslähmung"
        en: "Phrenic nerve palsy"
        fr: "Paralysie du nerf phrénique"
      - id: horner
        de: "Horner-Syndrom"
        en: "Horner’s syndrome"
        fr: "Syndrome de Horner"
      - id: pneumo_block
        de: "Pneumothorax (supra/interskalenär)"
        en: "Pneumothorax"
        fr: "Pneumothorax"
      - id: verfahrenswechsel_block
        de: "Wechsel auf Allgemeinanästhesie"
        en: "Conversion to general anaesthesia"
        fr: "Conversion en anesthésie générale"
      - id: rescue_block
        de: "Rescue-Block erforderlich"
        en: "Rescue block required"
        fr: "Bloc de secours nécessaire"

  analgesie_medikation:
    opioide:
      - id: übelkeit
        de: "Übelkeit / Erbrechen"
        en: "Nausea / vomiting"
        fr: "Naussées / vomissements"
      - id: obstipation
        de: "Obstipation"
        en: "Constipation"
        fr: "Constipation"
      - id: atemdepression
        de: "Atemdepression"
        en: "Respiratory depression"
        fr: "Dépression respiratoire"
      - id: pruritus
        de: "Juckreiz"
        en: "Pruritus"
        fr: "Prurit"
      - id: delir
        de: "Verwirrtheit / Delir"
        en: "Confusion / delirium"
        fr: "Confusion / délire"
      - id: abhängigkeit
        de: "Abhängigkeit / Toleranz"
        en: "Dependence / tolerance"
        fr: "Dépendance / tolérance"

    nsaid_coxib:
      - id: giblutung
        de: "GI-Blutung / Ulkus"
        en: "GI bleeding / ulcer"
        fr: "Hémorragie GI / ulcère"
      - id: nierenversagen
        de: "Nierenfunktionsstörung"
        en: "Renal impairment"
        fr: "Insuffisance rénale"
      - id: bronchospasmus_nsaid
        de: "Analgetika-Asthma"
        en: "NSAID-induced bronchospasm"
        fr: "Asthme induit par AINS"

    metamizol:
      - id: agranulozytose
        de: "Agranulozytose"
        en: "Agranulocytosis"
        fr: "Agranulocytose"
      - id: leberschaden
        de: "Lebertoxizität"
        en: "Liver toxicity"
        fr: "Hépatotoxicité"

    paracetamol:
      - id: hepatotox
        de: "Leberversagen"
        en: "Liver failure"
        fr: "Insuffisance hépatique"

    clonidin:
      - id: brady_hypo
        de: "Bradykardie / Hypotonie"
        en: "Bradycardia / hypotension"
        fr: "Bradycardie / hypotension"
      - id: rebound
        de: "Rebound-Hypertonie"
        en: "Rebound hypertension"
        fr: "Hypertension rebond"

  pca_iv:
    - id: pca_overdose
      de: "Überdosierung / Atemdepression"
      en: "Overdose / respiratory depression"
      fr: "Surdosage / dépression respiratoire"
    - id: pumpenfehler
      de: "Pumpenfehlfunktion"
      en: "Pump malfunction"
      fr: "Dysfonctionnement de la pompe"
    - id: fremdbedienung
      de: "Bedienung durch Dritte"
      en: "Activation by third person"
      fr: "Activation par un tiers"

  transfusion_cellsaver:
    - id: transfusionsreaktion
      de: "Transfusionsreaktion"
      en: "Transfusion reaction"
      fr: "Réaction transfusionnelle"
    - id: infektion_blut
      de: "Infektionsübertragung"
      en: "Transmission of infection"
      fr: "Transmission d’infection"
    - id: hämolyse
      de: "Hämolyse / Luftembolie (Cellsaver)"
      en: "Hemolysis / air embolism (cell saver)"
      fr: "Hémolyse / embolie gazeuse (cell saver)"
